const countries = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", currency: "AFN" },
  { name: "Albania", code: "AL", flag: "🇦🇱", currency: "ALL" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", currency: "DZD" },
  { name: "Andorra", code: "AD", flag: "🇦🇩", currency: "EUR" },
  { name: "Angola", code: "AO", flag: "🇦🇴", currency: "AOA" },
  { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", currency: "XCD" },
  { name: "Argentina", code: "AR", flag: "🇦🇷", currency: "ARS" },
  { name: "Armenia", code: "AM", flag: "🇦🇲", currency: "AMD" },
  { name: "Australia", code: "AU", flag: "🇦🇺", currency: "AUD" },
  { name: "Austria", code: "AT", flag: "🇦🇹", currency: "EUR" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", currency: "AZN" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸", currency: "BSD" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭", currency: "BHD" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", currency: "BDT" },
  { name: "Barbados", code: "BB", flag: "🇧🇧", currency: "BBD" },
  { name: "Belarus", code: "BY", flag: "🇧🇾", currency: "BYN" },
  { name: "Belgium", code: "BE", flag: "🇧🇪", currency: "EUR" },
  { name: "Belize", code: "BZ", flag: "🇧🇿", currency: "BZD" },
  { name: "Benin", code: "BJ", flag: "🇧🇯", currency: "XOF" },
  { name: "Bhutan", code: "BT", flag: "🇧🇹", currency: "BTN" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴", currency: "BOB" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", currency: "BAM" },
  { name: "Botswana", code: "BW", flag: "🇧🇼", currency: "BWP" },
  { name: "Brazil", code: "BR", flag: "🇧🇷", currency: "BRL" },
  { name: "Brunei", code: "BN", flag: "🇧🇳", currency: "BND" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬", currency: "BGN" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", currency: "XOF" },
  { name: "Burundi", code: "BI", flag: "🇧🇮", currency: "BIF" },
  { name: "Cabo Verde", code: "CV", flag: "🇨🇻", currency: "CVE" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭", currency: "KHR" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲", currency: "XAF" },
  { name: "Canada", code: "CA", flag: "🇨🇦", currency: "CAD" },
  { name: "Central African Republic", code: "CF", flag: "🇨🇫", currency: "XAF" },
  { name: "Chad", code: "TD", flag: "🇹🇩", currency: "XAF" },
  { name: "Chile", code: "CL", flag: "🇨🇱", currency: "CLP" },
  { name: "China", code: "CN", flag: "🇨🇳", currency: "CNY" },
  { name: "Colombia", code: "CO", flag: "🇨🇴", currency: "COP" },
  { name: "Comoros", code: "KM", flag: "🇰🇲", currency: "KMF" },
  { name: "Congo", code: "CG", flag: "🇨🇬", currency: "XAF" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", currency: "CRC" },
  { name: "Croatia", code: "HR", flag: "🇭🇷", currency: "HRK" },
  { name: "Cuba", code: "CU", flag: "🇨🇺", currency: "CUP" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾", currency: "EUR" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿", currency: "CZK" },
  { name: "Democratic Republic of the Congo", code: "CD", flag: "🇨🇩", currency: "CDF" },
  { name: "Denmark", code: "DK", flag: "🇩🇰", currency: "DKK" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯", currency: "DJF" },
  { name: "Dominica", code: "DM", flag: "🇩🇲", currency: "XCD" },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴", currency: "DOP" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨", currency: "USD" },
  { name: "Egypt", code: "EG", flag: "🇪🇬", currency: "EGP" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻", currency: "USD" },
  { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", currency: "XAF" },
  { name: "Eritrea", code: "ER", flag: "🇪🇷", currency: "ERN" },
  { name: "Estonia", code: "EE", flag: "🇪🇪", currency: "EUR" },
  { name: "Eswatini", code: "SZ", flag: "🇸🇿", currency: "SZL" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹", currency: "ETB" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯", currency: "FJD" },
  { name: "Finland", code: "FI", flag: "🇫🇮", currency: "EUR" },
  { name: "France", code: "FR", flag: "🇫🇷", currency: "EUR" },
  { name: "Gabon", code: "GA", flag: "🇬🇦", currency: "XAF" },
  { name: "Gambia", code: "GM", flag: "🇬🇲", currency: "GMD" },
  { name: "Georgia", code: "GE", flag: "🇬🇪", currency: "GEL" },
  { name: "Germany", code: "DE", flag: "🇩🇪", currency: "EUR" },
  { name: "Ghana", code: "GH", flag: "🇬🇭", currency: "GHS" },
  { name: "Greece", code: "GR", flag: "🇬🇷", currency: "EUR" },
  { name: "Grenada", code: "GD", flag: "🇬🇩", currency: "XCD" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹", currency: "GTQ" },
  { name: "Guinea", code: "GN", flag: "🇬🇳", currency: "GNF" },
  { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", currency: "XOF" },
  { name: "Guyana", code: "GY", flag: "🇬🇾", currency: "GYD" },
  { name: "Haiti", code: "HT", flag: "🇭🇹", currency: "HTG" },
  { name: "Honduras", code: "HN", flag: "🇭🇳", currency: "HNL" },
  { name: "Hungary", code: "HU", flag: "🇭🇺", currency: "HUF" },
  { name: "Iceland", code: "IS", flag: "🇮🇸", currency: "ISK" },
  { name: "India", code: "IN", flag: "🇮🇳", currency: "INR" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", currency: "IDR" },
  { name: "Iran", code: "IR", flag: "🇮🇷", currency: "IRR" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", currency: "IQD" },
  { name: "Ireland", code: "IE", flag: "🇮🇪", currency: "EUR" },
  { name: "Israel", code: "IL", flag: "🇮🇱", currency: "ILS" },
  { name: "Italy", code: "IT", flag: "🇮🇹", currency: "EUR" },
  { name: "Ivory Coast", code: "CI", flag: "🇨🇮", currency: "XOF" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲", currency: "JMD" },
  { name: "Japan", code: "JP", flag: "🇯🇵", currency: "JPY" },
  { name: "Jordan", code: "JO", flag: "🇯🇴", currency: "JOD" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", currency: "KZT" },
  { name: "Kenya", code: "KE", flag: "🇰🇪", currency: "KES" },
  { name: "Kiribati", code: "KI", flag: "🇰🇮", currency: "AUD" },
  { name: "Kosovo", code: "XK", flag: "🇽🇰", currency: "EUR" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼", currency: "KWD" },
  { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", currency: "KGS" },
  { name: "Laos", code: "LA", flag: "🇱🇦", currency: "LAK" },
  { name: "Latvia", code: "LV", flag: "🇱🇻", currency: "EUR" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧", currency: "LBP" },
  { name: "Lesotho", code: "LS", flag: "🇱🇸", currency: "LSL" },
  { name: "Liberia", code: "LR", flag: "🇱🇷", currency: "LRD" },
  { name: "Libya", code: "LY", flag: "🇱🇾", currency: "LYD" },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮", currency: "CHF" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹", currency: "EUR" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺", currency: "EUR" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬", currency: "MGA" },
  { name: "Malawi", code: "MW", flag: "🇲🇼", currency: "MWK" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", currency: "MYR" },
  { name: "Maldives", code: "MV", flag: "🇲🇻", currency: "MVR" },
  { name: "Mali", code: "ML", flag: "🇲🇱", currency: "XOF" },
  { name: "Malta", code: "MT", flag: "🇲🇹", currency: "EUR" },
  { name: "Marshall Islands", code: "MH", flag: "🇲🇭", currency: "USD" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷", currency: "MRU" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺", currency: "MUR" },
  { name: "Mexico", code: "MX", flag: "🇲🇽", currency: "MXN" },
  { name: "Micronesia", code: "FM", flag: "🇫🇲", currency: "USD" },
  { name: "Moldova", code: "MD", flag: "🇲🇩", currency: "MDL" },
  { name: "Monaco", code: "MC", flag: "🇲🇨", currency: "EUR" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳", currency: "MNT" },
  { name: "Montenegro", code: "ME", flag: "🇲🇪", currency: "EUR" },
  { name: "Morocco", code: "MA", flag: "🇲🇦", currency: "MAD" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿", currency: "MZN" },
  { name: "Myanmar", code: "MM", flag: "🇲🇲", currency: "MMK" },
  { name: "Namibia", code: "NA", flag: "🇳🇦", currency: "NAD" },
  { name: "Nauru", code: "NR", flag: "🇳🇷", currency: "AUD" },
  { name: "Nepal", code: "NP", flag: "🇳🇵", currency: "NPR" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", currency: "EUR" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿", currency: "NZD" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮", currency: "NIO" },
  { name: "Niger", code: "NE", flag: "🇳🇪", currency: "XOF" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", currency: "NGN" },
  { name: "North Korea", code: "KP", flag: "🇰🇵", currency: "KPW" },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰", currency: "MKD" },
  { name: "Norway", code: "NO", flag: "🇳🇴", currency: "NOK" },
  { name: "Oman", code: "OM", flag: "🇴🇲", currency: "OMR" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", currency: "PKR" },
  { name: "Palau", code: "PW", flag: "🇵🇼", currency: "USD" },
  { name: "Palestine", code: "PS", flag: "🇵🇸", currency: "ILS" },
  { name: "Panama", code: "PA", flag: "🇵🇦", currency: "PAB" },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬", currency: "PGK" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾", currency: "PYG" },
  { name: "Peru", code: "PE", flag: "🇵🇪", currency: "PEN" },
  { name: "Philippines", code: "PH", flag: "🇵🇭", currency: "PHP" },
  { name: "Poland", code: "PL", flag: "🇵🇱", currency: "PLN" },
  { name: "Portugal", code: "PT", flag: "🇵🇹", currency: "EUR" },
  { name: "Qatar", code: "QA", flag: "🇶🇦", currency: "QAR" },
  { name: "Romania", code: "RO", flag: "🇷🇴", currency: "RON" },
  { name: "Russia", code: "RU", flag: "🇷🇺", currency: "RUB" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼", currency: "RWF" },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", currency: "XCD" },
  { name: "Saint Lucia", code: "LC", flag: "🇱🇨", currency: "XCD" },
  { name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨", currency: "XCD" },
  { name: "Samoa", code: "WS", flag: "🇼🇸", currency: "WST" },
  { name: "San Marino", code: "SM", flag: "🇸🇲", currency: "EUR" },
  { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", currency: "STN" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", currency: "SAR" },
  { name: "Senegal", code: "SN", flag: "🇸🇳", currency: "XOF" },
  { name: "Serbia", code: "RS", flag: "🇷🇸", currency: "RSD" },
  { name: "Seychelles", code: "SC", flag: "🇸🇨", currency: "SCR" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱", currency: "SLL" },
  { name: "Singapore", code: "SG", flag: "🇸🇬", currency: "SGD" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰", currency: "EUR" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮", currency: "EUR" },
  { name: "Solomon Islands", code: "SB", flag: "🇸🇧", currency: "SBD" },
  { name: "Somalia", code: "SO", flag: "🇸🇴", currency: "SOS" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", currency: "ZAR" },
  { name: "South Korea", code: "KR", flag: "🇰🇷", currency: "KRW" },
  { name: "South Sudan", code: "SS", flag: "🇸🇸", currency: "SSP" },
  { name: "Spain", code: "ES", flag: "🇪🇸", currency: "EUR" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", currency: "LKR" },
  { name: "Sudan", code: "SD", flag: "🇸🇩", currency: "SDG" },
  { name: "Suriname", code: "SR", flag: "🇸🇷", currency: "SRD" },
  { name: "Sweden", code: "SE", flag: "🇸🇪", currency: "SEK" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", currency: "CHF" },
  { name: "Syria", code: "SY", flag: "🇸🇾", currency: "SYP" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼", currency: "TWD" },
  { name: "Tajikistan", code: "TJ", flag: "🇹🇯", currency: "TJS" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿", currency: "TZS" },
  { name: "Thailand", code: "TH", flag: "🇹🇭", currency: "THB" },
  { name: "Timor-Leste", code: "TL", flag: "🇹🇱", currency: "USD" },
  { name: "Togo", code: "TG", flag: "🇹🇬", currency: "XOF" },
  { name: "Tonga", code: "TO", flag: "🇹🇴", currency: "TOP" },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", currency: "TTD" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳", currency: "TND" },
  { name: "Turkey", code: "TR", flag: "🇹🇷", currency: "TRY" },
  { name: "Turkmenistan", code: "TM", flag: "🇹🇲", currency: "TMT" },
  { name: "Tuvalu", code: "TV", flag: "🇹🇻", currency: "AUD" },
  { name: "Uganda", code: "UG", flag: "🇺🇬", currency: "UGX" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", currency: "UAH" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", currency: "AED" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", currency: "GBP" },
  { name: "United States", code: "US", flag: "🇺🇸", currency: "USD" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", currency: "UYU" },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", currency: "UZS" },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺", currency: "VUV" },
  { name: "Vatican City", code: "VA", flag: "🇻🇦", currency: "EUR" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", currency: "VES" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", currency: "VND" },
  { name: "Yemen", code: "YE", flag: "🇾🇪", currency: "YER" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲", currency: "ZMW" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", currency: "ZWL" }
];

export default countries;